// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Json          = require("bs-json/src/Json.js");
var Fetch         = require("bs-fetch/src/Fetch.js");
var Element       = require("../../Element.js");
var ServicesConst = require("../../services/ServicesConst.js");

function get() {
  return fetch(ServicesConst.server_url + "/getData").then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Element.Decode[/* to_element_list */2](json));
              }));
}

function getStorage() {
  return fetch(ServicesConst.server_url + "/getDataStorage").then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Element.Decode[/* to_element_list */2](json));
              }));
}

function set(elementsList) {
  return Promise.resolve(fetch(ServicesConst.server_url + "/setData", Fetch.RequestInit[/* make */0](/* Some */[/* Post */2], /* None */0, /* Some */[Json.stringify(Element.Encode[/* to_element_list */2](elementsList))], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* () */0)));
}

exports.get        = get;
exports.getStorage = getStorage;
exports.set        = set;
/* Element Not a pure module */
